# Generated by Django 5.1.2 on 2024-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="sharmanik", max_length=256, unique=True),
        ),
    ]
