# Generated by Django 5.1.2 on 2024-11-03 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
